# Generated by Django 4.1.13 on 2024-02-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RentApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="user",
            new_name="user_id",
        ),
    ]
