# Generated by Django 4.1.13 on 2024-02-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RentApp", "0003_alter_rentappusers_email_alter_rentappusers_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="user_id",
            new_name="user",
        ),
    ]
